### ISSUE TITLE
Under Raspberry pi, camorama is producing false color images

### ISSUE THREAD

**Issue by Plutonium5793** [alessio/camorama#8] opened 2017-03-09 23:10 UTC
I compiled the current version of camorama-master under raspian on a Rpi.  It finds the camera, but the image display is way too intense with saturated colors.  half of the image is white.  The camera is working well under windows,and fedora linux.

**Comment by mchehab** [comment] 2022-03-19 15:08
I'm closing this issue, due to the lack of news about it. If this is still reproducible with recent Kernels, please re-open and provide more details about what camera(s) are causing issues with Camorama.

**Closed by mchehab** 2022-03-19 15:08 UTC
